spring:
  application:
    name: user-service

  datasource:
    url: ${url}
    username: root
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    compatibility-verifier:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Microservice-Realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    # optional
server:
  port: 8081

#Keycloak config
keycloak:
  server-url: http://localhost:8080
  realm: Microservice-Realm
  client-id: userSerive
  client-secret: ${secret}

logging:
  level:
    org:
      springframework:
        web:
          client: debug
        security: trace
