spring:
  application:
    name: Inventory-service

  datasource:
    url: ${url}
    password: ${dbPassword}
    username: root

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    compatibility-verifier:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Microservice-Realm

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: inventory-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.inventoryService.dto



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    # optional

  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: inventory-Server:localhost:8084


server:
  port: 8084

logging:
  level:
    org:
      springframework:
        web:
          client: debug
        security: trace
