spring:
  application:
    name: cartService

  data:
    mongodb:
      uri: mongodb://localhost:27017/e-commerce

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Microservice-Realm
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cart-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # Trust all packages for deserialization
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.cartService.dto.KafkaDto

  cloud:
    compatibility-verifier:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    # optional

  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: cartService:localhost:8083

server:
  port: 8083

logging:
  level:
    org:
      springframework:
        web:
          client: debug
        security: trace
