spring:
  application:
    name: productService

  data:
    mongodb:
      uri: mongodb://localhost:27017/e-commerce

  cloud:
    compatibility-verifier:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    # optional


server:
  port: 8082

logging:
  level:
    org:
      springframework:
        web:
          client: debug
        security: trace