spring:
  application:
    name: productService

  data:
    mongodb:
      uri: mongodb://localhost:27017/e-commerce


server:
  port: 8082

logging:
  level:
    org:
      springframework:
        web:
          client: debug
        security: trace